version: "3.3"
services:
  # api:
  #   build: .
  #   image: usa-api
  #   container_name: usa_backend
  #   restart: always
  #   volumes:
  #     - .:/usr/src/app
  #   env_file:
  #     - .env
  #   networks:
  #     - usa-network
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - mongo

  mongo:
    image: mongo:latest
    container_name: usa_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGODB_DATABASE: usa
    networks:
      - usa-network
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
networks:
  usa-network:
    driver: bridge
